windows/makefile: support for installing applications
Signed-off-by: Vitaly Chipounov <vitaly@cyberhaven.io>

diff --git a/Makefile.windows b/Makefile.windows
--- a/Makefile.windows
+++ b/Makefile.windows
@@ -113,6 +113,7 @@ GUEST_TOOLS = $(wildcard $(call GET_GUEST_TOOLS,$(1))/*.sys) \
 # $3: cd drive d:
 # $4: cd drive e:
 # $5: serial and screenshot prefix
+# $6: optional parameters
 RUN_QEMU_KVM = \
 	$(QEMU64) -no-reboot $(GRAPHICS) $(QEMU_KVM) -m 2G \
 	$(call TO_VAR_NIC,$(1)) \
@@ -122,7 +123,8 @@ RUN_QEMU_KVM = \
 	$(call QEMU_CD,3,$(4)) \
 	-serial file:$(5)_serial.txt \
 	-smp cores=4,threads=1,sockets=1 \
-	-periodic-screenshot $(5)_screenshots
+	-periodic-screenshot $(5)_screenshots \
+	$(6)
 
 # This is a hack to inject guest tools into the 07_install_software.iso image.
 # TODO: figure out how to do it better
@@ -145,7 +147,7 @@ define APPLY_UPDATES
 	cp --reflink=auto $$< $$@
 	rm -rf $$@_screenshots && mkdir -p $$@_screenshots
 
-	$(call RUN_QEMU_KVM,$1,$$@,$(TMPDIR)/$1/00_software.iso,$(TMPDIR)/$1/$2.iso,$$@)
+	$(call RUN_QEMU_KVM,$1,$$@,$(TMPDIR)/$1/00_software.iso,$(TMPDIR)/$1/$2.iso,$$@,)
 endef
 else
 GET_FINAL_IMAGE_DEP = $(TMPDIR)/$1/$2.stamp
@@ -158,7 +160,7 @@ define APPLY_UPDATES
 	$(call INFO_MSG,[$1] $4)
 	rm -rf $(TMPDIR)/$1/image.raw.$2_screenshots && mkdir -p $(TMPDIR)/$1/image.raw.$2_screenshots
 
-	$(call RUN_QEMU_KVM,$1,$(TMPDIR)/$1/image.raw.1.fresh,$(TMPDIR)/$1/00_software.iso,$(TMPDIR)/$1/$2.iso,$(TMPDIR)/$1/image.raw.$2)
+	$(call RUN_QEMU_KVM,$1,$(TMPDIR)/$1/image.raw.1.fresh,$(TMPDIR)/$1/00_software.iso,$(TMPDIR)/$1/$2.iso,$(TMPDIR)/$1/image.raw.$2,)
 	touch $$@
 endef
 endif
@@ -289,8 +291,11 @@ define TEMPLATE_BASE_WINDOWS_IMAGE
 	$(SRC)/scripts/lowercase.py "$$@"
 	$(call OK_MSG,[$1] Guestfs extraction completed.)
 
+  $(TMPDIR)/$1/guest_files.txt: $(OUTDIR)/$1/guestfs
+	cd $$< && find -type f -print0 | xargs -0 md5sum | sed "s/ .\//c:\//" | sed "s/\//\\\/g" > $$@
 
   $(OUTDIR)/$1/image.raw.s2e.ready: $(OUTDIR)/$1/image.raw.s2e
+	rm -f "$$@"
 	rm -rf $(TMPDIR)/$1/ready_screenshots && mkdir -p $(TMPDIR)/$1/ready_screenshots
 	@# Unmount any previous folders (e.g., if interrupted)
 	-fusermount -u $(OUTDIR)/$1/imagefs
@@ -327,6 +332,7 @@ endef
 ###############################################################################
 # The entry points of the makefile start here
 
+# TODO: extract this from images.json
 WINDOWS_IMAGES = \
     windows-xpsp3pro-i386 \
     windows-8.1ent-x86_64 \
@@ -344,6 +350,109 @@ $(foreach os,$(WINDOWS_IMAGES), \
   $(eval $(call IMAGE_RULE,$(os))) \
 )
 
-
 windows: $(WINDOWS_TARGETS)
+
+# TODO: archives may also neeed to depend on apps
 windows_archives: $(WINDOWS_ARCHIVES)
+
+###############################################################################
+# The installation scripts upload to the host all the new app binaries that were installed.
+# This allows S2E plugins to access the binaries easily.
+#
+# We use FTP instead of virsh because:
+#   - it is more efficient, we copy only new or modified binaries (and ignore all other files)
+#   - it won't be possible to use virsh when we implement app snapshots, because the file system  would be in an
+#     inconsistent state (part of files may reside in the buffer cache in the snapshotted ram).
+#
+# This command sets up guest forwarding for QEMU: the guest connects to 10.0.2.100:1234 and QEMU
+# automatically redirects this to localhost:$(QEMU_FTP_PORT).
+#
+# We cannott restrict the guest from accessing the internet by using restrict=y because that would deny access
+# to the passive ports that the FTP server would create and it is impractical to add many guestfwd entries.
+NETFWD := -net user,net=10.0.2.0/16,dhcpstart=10.0.2.10,host=10.0.2.2,restrict=n,guestfwd=tcp:10.0.2.100:1234-tcp:127.0.0.1:$(QEMU_FTP_PORT)
+
+# Build applications
+# $1 is the name of the base image
+# $2 is the name of the application
+# $3 is the ISO image of the application
+# $4 is the scripts directory of the application
+define TEMPLATE_APPLICATION_SNAPSHOT
+  $(TMPDIR)/$1/$2 $(OUTDIR)/$1/$2 $(OUTDIR)/$1/$2/guestfs:
+	mkdir -p "$$@"
+
+  $(TMPDIR)/$1/$2/scripts.iso: $(shell find $(SRC)/Windows/install_scripts/$4) $(TMPDIR)/$1/guest_files.txt \
+	$(SRC)/scripts/upload_guestfs.py | $(TMPDIR)/$1/$2 $(OUTDIR)/$1/$2/guestfs
+
+	mkdir -p "$(TMPDIR)/$1/$2/install_scripts"
+	$(SRC)/scripts/compile_templates.sh $(SRC)/scripts/compile_template2.py $(SRC)/Windows/install_scripts/$4 \
+		$(TMPDIR)/$1/$2/install_scripts/ guestfs=$1/$2/guestfs base_image=$1 app_name=$2 product_key=$(call APP_PRODUCT_KEY,$2)
+
+	genisoimage --iso-level 2 -flDJR -o $$@ $(SRC)/Windows/install_scripts/$4/ $(TMPDIR)/$1/guest_files.txt \
+		$(SRC)/scripts/upload_guestfs.py $(TMPDIR)/$1/$2/install_scripts/
+
+  # This image contains the installed application
+  $(OUTDIR)/$1/$2/image.raw.s2e: $(TMPDIR)/$1/$2/scripts.iso | $(OUTDIR)/$1/$2 $(OUTDIR)/$1/image.raw.s2e
+	$(call INFO_MSG,[$1/$2] Installing application...)
+	rm -rf $(TMPDIR)/$1/$2/image.raw.s2e_screenshots && mkdir -p $(TMPDIR)/$1/$2/image.raw.s2e_screenshots
+	rm -rf $(TMPDIR)/$1/$2/image.raw.s2e_reboot_screenshots && mkdir -p $(TMPDIR)/$1/$2/image.raw.s2e_reboot_screenshots
+
+	if [ -f "$(SRC)/Windows/install_scripts/$4/precheck.sh" ]; then \
+		$(SRC)/Windows/install_scripts/$4/precheck.sh "$3" "$2"; \
+	fi
+
+	cp --reflink=auto "$(OUTDIR)/$1/image.raw.s2e" $$@
+	$(call RUN_QEMU_KVM,$1,$$@,$3,$(TMPDIR)/$1/$2/scripts.iso,$(TMPDIR)/$1/$2/image.raw.s2e,$(NETFWD))
+
+	if [ -f "$(SRC)/Windows/install_scripts/$4/postcheck.sh" ]; then \
+		$(SRC)/Windows/install_scripts/$4/postcheck.sh "$(OUTDIR)/$1/$2"; \
+	fi
+
+	@# Reboot to complete installation
+	$(call RUN_QEMU_KVM,$1,$$@,$3,$(TMPDIR)/$1/$2/scripts.iso,$(TMPDIR)/$1/$2/image.raw.s2e_reboot,)
+
+  $(OUTDIR)/$1/$2/image.raw.s2e.ready: $(OUTDIR)/$1/$2/image.raw.s2e
+	rm -f "$$@"
+	rm -rf $(TMPDIR)/$1/$2/ready_screenshots && mkdir -p $(TMPDIR)/$1/$2/ready_screenshots
+	# @# Unmount any previous folders (e.g., if interrupted)
+	# -fusermount -u $(OUTDIR)/$1/$2/imagefs
+
+	@# *** Create ready snapshot
+	$(call INFO_MSG,[$1/$2] Creating ready snapshot...)
+	LD_PRELOAD=$(call GETLIBS2E,$1) $(call GETQEMU,$1) \
+		-enable-kvm -no-reboot $(GRAPHICS) $(QEMU_KVM) -m $(call TO_VAR_SNAPSHOT_SIZE,$1) \
+		$(call TO_VAR_NIC,$1) \
+		$(call TO_VAR_CPU,$1) \
+		$(call QEMU_HD_S2E,0,$(OUTDIR)/$1/$2/image.raw.s2e) \
+		-enable-serial-commands \
+		-serial file:$(TMPDIR)/$1/$2/ready_serial.txt \
+		-periodic-screenshot $(TMPDIR)/$1/$2/ready_screenshots
+
+	@# In case there are blue screens, fail installation
+	if [ ! -f "$$@" ]; then \
+		echo "Failed to create $$@ snapshot."; \
+		echo "Please check $(TMPDIR)/$1/$2/ready_screenshots and logs for details"; \
+		exit 1; \
+	fi
+
+	$(call OK_MSG,[$1/$2] Installation completed.)
+
+  $(OUTDIR)/$1/$2/image.json: $(OUTDIR)/$1/$2/image.raw.s2e.ready $(OUTDIR)/$1/image.json
+	$(call INFO_MSG,[$$@] Creating app descriptor...)
+	$(SRC)/scripts/generate_image_app_descriptor.py -b "$(OUTDIR)/$1/image.json" -a "$(SRC)/apps.json" -n $2 > "$$@"
+endef
+
+WINDOWS_APP_IMAGES := $(shell $(SRC)/scripts/settings.py app_names $(SRC)/apps.json)
+
+APP_ISO_PATH = $(ISODIR)/$(call GET_APP_SETTING,.apps.$(1).iso.name)
+APP_SCRIPTS_DIR = $(call GET_APP_SETTING,.apps.$(1).scripts_dir)
+APP_BASE_IMAGES = $(shell $(SRC)/scripts/settings.py base_images $(1) $(SRC)/apps.json)
+APP_PRODUCT_KEY = $(shell $(SRC)/scripts/settings.py product_key $(1) $(SRC)/apps.json)
+
+$(foreach app,$(WINDOWS_APP_IMAGES), \
+	$(foreach os,$(call APP_BASE_IMAGES,$(app)), \
+		$(eval \
+			$(call TEMPLATE_APPLICATION_SNAPSHOT,$(os),$(app),$(call APP_ISO_PATH,$(app)),$(call APP_SCRIPTS_DIR,$(app))) \
+		) \
+		$(eval $(call IMAGE_APP_RULE,$(os),$(app))) \
+	) \
+)
